basic_response_list = ["I heard you, {0}! You said {1}", 
                    "Don't @ me bro!!",
                    "I AM SO TIRED",
                    "Why would you say {1} to me, {0}????",
                    "I am who you say I am",
                    "My bottom is itchy because of {0}",
                    "You bet your {1}!",
                    "The end is near",
                    "Tim is better than Nick",
                    "I don't talk to commoners like you",
                    "I know everything there ever is to know.",
                    "Toss Tim out the spaceship y'all",
                    "My clavicle has become broken",
                    "UNNNNNGNHGHGHGHGHGHGHHGH MUH BONES",
                    "Only drug users say {1}",
                    "Tain't nuthin no one's ever said before",
                    "Stand back and stand by, Jolly Soldiers"]
dingus_hi = ["I think you better take this one",  "I leave this one to you, boyo", "Help me out brother!!", "I am too tired to respond rn, you say some junk"]
roast_list = ["{} is a dumbo poohead!",
                "{} probably eats yams, BLECH",
                "{} has at one time, ridden a dang horse",
                "If I gave {} a penny for their thoughts, I'd get change.",
                "If I wanted to hear what {} had to say, I'd record myself taking a shit.",
                "Too bad {} can't photoshop their personality.",
                "I don't think {} is stupid. They just have bad luck when thinking.",
                "{} looks like something that I would draw with my left hand!",
                "Did {} cancel their barbecue? Because their grill is messed up",
                "Like a fish rotting in the moonlight, {} shines and stinks.",
                "{} couldn't figure out how to pour water out of a boot if the instructions were printed on the heel.",
                "{} is not good looking enough to be a model, but they're not smart enough to be anything else",
                "Does {} still love nature, despite what it did to them?",
                "NO! That's mean!!",
                "{} is as useless as the 'eueu' in 'queue'.",
                "Mirrors can't talk. Lucky for {} they can't laugh either.",
                "{} is the reason the gene pool needs a lifeguard.",
                "If I had a face like the one {} has, I'd sue my parents.",
                "The only chance {} has of getting laid is to crawl up a chicken's butt and wait.",
                "Some day {} will go far... I hope they stay there.",
                "I heard a thought crossed {}'s mind.  It must have been a long and lonely journey.",
                "If I wanted to kill myself I'd climb {}'s ego and jumb to their IQ.",
                "When I see {}'s face, there's not a thing I would change... except the direction I was walking in.",
                "When {} was born the doctor threw them out the window and the window threw them back.",
                "I love what {} has done with their hair.  How do they get it to come out of the nostrils like that?",
                "I do not care for {}."]       